before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip
  - unzip -d /tmp /tmp/terraform.zip
  - sudo mv /tmp/terraform /usr/local/bin/terraform

install:
  - terraform init -backend=false

script:
  - terraform validate -var-file=terraform.tfvars.default terraform
