#!/usr/bin/env python

#
# Gets the principal for the account associated with
# the current user.
#

import boto3


def main():
    client = boto3.client('sts')
    response = client.get_caller_identity()
    print('arn:aws:iam::{}:root'.format(response['Account']))


if __name__ == '__main__':
    main()
